import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profilepic.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import lightbulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark dark:text-light w-full min-h-screen">
        <Layout className="pt-0 md:pt-16 sm:!p-8 sm:pt-8">
          <div className="flex items-center w-full lg:flex-col">
            <div className="w-1/2 lg:flex justify-center md:!w-full">
            <Image
                src={profilePic}
                alt="Image for home"
                priority
                // sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
                className="w-[60%] relative rounded-2xl"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center lg:w-full lg:text-center ">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-5xl !text-left xl:!text-4xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base md:text-sm sm:text-xs">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start lg:self-center">
                <Link
                  href="/resume.pdf"
                  target="_blank"
                  download={true}
                  className="bg-dark flex items-center justify-center text-light py-3 px-6 rounded-lg font-semibold text-md hover:bg-light hover:text-dark border-2 border-solid border-transparent transition duration-200 hover:border-dark dark:bg-light dark:text-dark dark:hover:bg-dark dark:hover:text-light dark:hover:border-light md:p-2 md:px-4 md:text-base"
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:joeswaroopmakena@gmail.com"
                  target="_blank"
                  className="ml-4 text-md font-medium underline dark:text-light text-dark md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8  inline-block w-24">
          <Image
            src={lightbulb}
            className="w-full h-auto md:hidden lg:inline-block lg:w-[4.9rem] xl:hidden"
          />
        </div>
      </main>
    </>
  );
}
